### ISSUE TITLE
Feature: to add additional plugins to the image/container

### ISSUE THREAD

**Issue by giovanne123** [martinwiest/WeeWX-Docker#1]
Would be fine to have the possibility to add additional plugins:

Currently I need:
- mqtt
- mysql

1) Quick Workaound to get it persitant into the image
2) Comfortable solution by e.g. putting plugin info to config dir and installed automatically

Btw: Thanks for your work providing this image. Very helpfull to me getting started with weewx.
Excuse me I'm ralatively new to weewx (and also docker) and starting to learn it both more in details...

**Comment by giovanne123** [comment]
1.

- mysql: ok for mysql plugin seems to be already integrated in weewx/your image
Using mysqld from host (not inside container) allowing to use it directly after configuring mysql in weewx.conf and starting container with bind _-v "/var/run/mysqld/mysqld.sock":"/var/run/mysqld/mysqld.sock"_ 

- mqtt: configured in weewx.conf without adding plugin, 
weewx ist starting, can't see any error so far but mqtt isn't publishing something (so need to integrate plugin before)...

**Comment by martinwiest** [comment]
Added python3-paho-mqtt to be installed per apt in the dockerfile, please rebuild your container.
You can simple put your plugins and skins to the config dir. (as zip-files). They get installed at container start.
Tested this with the weewx-mqtt plugin you linked.

```bash
Aug  9 00:51:56 23d71b516fa3 user.info weewx[28] INFO user.mqtt: service version is 0.23                                                 
Aug  9 00:51:56 23d71b516fa3 user.info weewx[28] INFO user.mqtt: binding to archive                                                      
Aug  9 00:51:56 23d71b516fa3 user.info weewx[28] INFO user.mqtt: topic is weather                                                        
Aug  9 00:51:56 23d71b516fa3 user.info weewx[28] INFO user.mqtt: data will be uploaded to INSERT_SERVER_URL_HERE  
```
Logs per: docker exec -it weewx tail -f 100 /var/log/messages 

mysql - i think about a db-container started together with the weewx-container per docker-compose

**Comment by giovanne123** [comment]
Thanks, I will test next week (after vacation).

For the db I think I will stay with my already running db to have all my data at one place.

**Comment by giovanne123** [comment]
Thanks a lot, plugin auto installation is working :-) 
Tested also with mqtt https://github.com/matthewwall/weewx-mqtt/archive/master.zip and data/topics are published :-)

For auto skin install I will test maybe later when I find additional interesting skin (currently I'm using: https://neoground.com/docs/neowx-material/index), 
because I already binding/mounting the skins dir in container by _-v "/home/pi/weewx_data/skins":"/home/weewx/skins"_ (https://github.com/martinwiest/WeeWX-Docker/issues/2)
