### ISSUE TITLE
newbie ...

### ISSUE THREAD

**Issue by belidi** [martinwiest/WeeWX-Docker#5]
Question from someone new to docker:
I run the commands (with sudo) as shown with docker-compose. But there is no creation of "home/weewx" and therefore not possible to modify weewx.conf. by opening: http://ip-address-of-your-pi , I see the weather data.
Is it possible to use the scripts included in weewx: wee_extension, ...
If yes, how can we do it?

**Comment by martinwiest** [comment]
If you clone this repo to your maschine, you will find a dir named "config" inside. Put your modified weewx.conf here before starting the container with docker compose. You can also put your own weewx scripts and plugins here. Take a look in the README under "Customation - Use of skins and plugins"

To use the basic scripts of weewx you have to enter the running container in interactiv mode:

> docker-compose exec weewx /bin/bash
>
> root@0cff335b7b9f:/home/weewx#
