### ISSUE TITLE
Question: usage of new weewx version?

### ISSUE THREAD

**Issue by giovanne123** [martinwiest/WeeWX-Docker#6]
Hi Martin,
first of all still thanks for your WeeWx Container, I'm still using it.
It is running well and normally no need for an update - "never change a running system" ;-)

But, I thought to ask I you already have tried/tested a newer/newest version?
E.g.: https://weewx.com/downloads/weewx-4.6.2.tar.gz

Do you think editing the "Dockerfile" should be enough?

Maybe I will give it a try in an additinal container and the possibility to switch back in case of issues.

**Comment by martinwiest** [comment]
Hi Giovanne123, 
thank you for your feedback.

The test with the new version was successful. I updated the dockerfile and the multiarchimage.

**Comment by giovanne123** [comment]
@martinwiest, thank you - comfirm it is working with new version.
